name: docs_pages_workflow

# execute this workflow automatically when we push to master
on:
  push:
    branches: [ main ]

jobs:

  build_docs_job:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-doctools.txt

      - name: Make the Sphinx Docs
        run: |
          # make -C docs clean 
          # sphinx-apidoc -f -o docs/source . -H Test -e -t docs/source/_templates
          # make -C docs html
          sphinx-apidoc -e -f -d 5 --templatedir docs/_templates/apidoc -o docs/reference/ lpmd "lpmd/tests/*"
          sphinx-build -b html docs/ docs/_build/html/

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/_build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/_build/html