name: lpmd Module Dev

on: push

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-latest, macos-10.15]
        python-version: ["3.9"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependecies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r requirements-devtools.txt

      - name: PyTest
        run: |
          pytest --cov=lpmd lpmd
          coverage report
          coverage xml

      - name: Upload PyTest Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: PyTest Results (Python 3.9)
          path: ./*.xml

      - name: Download Artifacts
        if: success()
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
